{
  "armor": {
    "make": [
      "Iron",
      "Steel",
      "Ironwood",
      "Ebon",
      "Bronze",
      "Silver",
      "Oak",
      "Rusted",
      "Leather",
      "Scale",
      "Chainmail",
      "Mithril",
      "Silk",
      "Shell",
      "Great Shell",
      "Bone",
      "Obsidian",
      "Copper",
      "Adamantine",
      "Stone"
    ],
    "type": [
      "Helmet",
      "Gauntlets",
      "Greaves",
      "Boots",
      "Breastplate",
      "Pauldrons",
      "Belt",
      "Shield",
      "Buckler",
      "Tunic",
      "Weave"
    ],
    "element": [
      "Ice",
      "Frost",
      "Fire",
      "Flame",
      "Water",
      "Sea",
      "Blood",
      "Life",
      "Death",
      "Chaos",
      "Law",
      "Fear",
      "Poison",
      "Shadow",
      "Night",
      "Day",
      "Light",
      "Shadow"
    ]
  }
}