{
  "plot": {
    "protag": [
      "man",
      "woman",
      "knight",
      "king",
      "queen",
      "dragon",
      "lord",
      "baron",
      "lion",
      "horse",
      "God",
      "distaster",
      "prostitute",
      "mage",
      "wizard",
      "witch",
      "templar",
      "priest",
      "scribe",
      "scribe",
      "group of rebels",
      "ship",
      "lady",
      "prince",
      "princess",
      "pauper",
      "terribly ill person",
      "necromancer",
      "sorcerer",
      "bandit",
      "war",
      "shaman",
      "slaver",
      "mercenary",
      "bard",
      "pirate",
      "cocubine",
      "cannibal",
      "sprite",
      "fae",
      "corpse",
      "elemental",
      "wyvern",
      "owlbear",
      "manticore",
      "hero",
      "slime",
      "wildfire",
      "warlord",
      "explorer",
      "swashbuckler"
    ],
    "means": [
      "must kill",
      "marries",
      "fights",
      "dies because of",
      "kills",
      "dies along with",
      "is",
      "taxes",
      "tortures",
      "becomes",
      "flees",
      "is in love with",
      "bargains with",
      "outwits",
      "lies to",
      "poisons",
      "tricks",
      "tracks down",
      "seeks",
      "burns",
      "creates",
      "is saddened by",
      "seeks refuge from",
      "destroys",
      "steals",
      "houses",
      "becomes",
      "tracks down",
      "possesses",
      "is possessed by",
      "baffles",
      "exorcises",
      "creates",
      "supplicates",
      "usurps",
      "saves",
      "blames",
      "places a bounty on",
      "condems",
      "marks",
      "identifies",
      "discovers"
    ],
    "thing": [
      "a despot",
      "a demon",
      "a dragon",
      "an army",
      "a princess",
      "a murderer",
      "in battle",
      "a king",
      "a queen",
      "himself",
      "a wizard",
      "a witch",
      "a mage",
      "a templar",
      "a village",
      "a city",
      "a river",
      "a lake",
      "a burglar",
      "a relative",
      "a temple",
      "an ocean",
      "a monster",
      "a weapon",
      "all hope",
      "a ghost",
      "one last time",
      "a sea",
      "a ship",
      "a plane",
      "the elements",
      "the elves",
      "the dwarves",
      "kobolds",
      "the undead",
      "ghouls",
      "a priest",
      "a warlock",
      "an assassin",
      "a witch doctor",
      "a noble",
      "an imp"
    ]
  }
}