{
  "weapon": {
    "make": [
      "Iron",
      "Steel",
      "Ironwood",
      "Ebon",
      "Bronze",
      "Silver",
      "Oak",
      "Rusted",
      "Tusk",
      "Bone",
      "Obsidian",
      "Copper",
      "Adamantine",
      "Stone"
    ],
    "type": [
      "Warhammer",
      "Mace",
      "Club",
      "Short Sword",
      "Long Sword",
      "Bastard Sword",
      "Long Bow",
      "Short Bow",
      "Crossbow",
      "Javelin",
      "Spear",
      "Dagger",
      "War Axe",
      "Scythe",
      "Staff",
      "Halbred",
      "Great Bow",
      "Hand Crossbow",
      "Knife",
      "Machete",
      "Rapier",
      "Trident",
      "Katar",
      "Fist Wraps"
    ],
    "element": [
      "Ice",
      "Frost",
      "Fire",
      "Flame",
      "Water",
      "Sea",
      "Blood",
      "Life",
      "Death",
      "Chaos",
      "Law",
      "Fear",
      "Poison",
      "Shadow",
      "Night",
      "Day",
      "Shade",
      "Illumination"
    ]
  }
}